### PR TITLE
OOP school library: add Person, Student and Teacher classes

### PR DESCRIPTION
**Pull request by jssol**
## Project requirements

- Created class `Person` with  the following:
  - Instance vars: `@id`, `@name`, and `@age`.
  - Constructor with `name`,  `age`, and `parent_permission` as parameter. `name` and `parent_permission` are optional and have default values of `"Unknown"` and `true`.
  - Getters for `@id`, `@name`, and `@age`.
  - Setters for `@name` and `@age`.
  - Private method `is_of_age?` that returns `true` if `@age` is greater or equal to 18 and `false` otherwise.
  - Public method `can_use_services?` that returns `true` if person is of age or if they have permission from parents.
- Created class `Student` with the following:
  - Inherits from `Person`.
  - Constructor extends parent's constructor by adding `@classroom` and a parameter for it.
  - Method `play_hooky` that returns `"¯\(ツ)/¯"`.
- Created class `Teacher` with the following:
  - Inherits from `Person`.
  - Constructor extends parent's constructor by adding `@specialization` and a parameter for it.
  - Override `can_use_services?` so it always returns `true`.
- Each class is saved in a separate file.

### CODE REVIEW

**Comment by jssol** [comment]
## :warning: Help needed :speaking_head:
> I am getting these errors and I can't find a solution. It would be kind to give me a hint as how to get rid of them.
```
Offenses:

person.rb:1:1: E: Lint/Syntax: class definition in method body
(Using Ruby 2.5 parser; configure using TargetRubyVersion parameter, under AllCops)
class Person
^^^^^
person.rb:6:35: E: Lint/Syntax: unexpected token tIDENTIFIER
(Using Ruby 2.5 parser; configure using TargetRubyVersion parameter, under AllCops)
  def initialize(name: 'Unknown', age, parent_permission: true)
                                  ^^^
student.rb:6:31: E: Lint/Syntax: unexpected token tCOMMA
(Using Ruby 2.5 parser; configure using TargetRubyVersion parameter, under AllCops)
    super(name: 'Unknown', age, parent_permission: true)
                              ^
student.rb:13:1: E: Lint/Syntax: unexpected token $end
(Using Ruby 2.5 parser; configure using TargetRubyVersion parameter, under AllCops)
teacher.rb:6:31: E: Lint/Syntax: unexpected token tRPAREN
(Using Ruby 2.5 parser; configure using TargetRubyVersion parameter, under AllCops)
    super(name: 'Unknown', age)
                              ^
teacher.rb:14:1: E: Lint/Syntax: unexpected token $end
(Using Ruby 2.5 parser; configure using TargetRubyVersion parameter, under AllCops)

4 files inspected, 6 offenses detected
```

**Comment by VICTOR-CHUKWU** [comment]
what is your slack name so i can help you

**Comment by jssol** [comment]
> what is your slack name so i can help you

@VICTOR-CHUKWU 
My name is Jonathan Sivahera on slack

**Comment by VICTOR-CHUKWU** [comment]
come to slack then

**Review by VICTOR-CHUKWU — APPROVED** [review]
Hi @jssol , 
# STATUS: APPROVED! 🥇 💯 
done

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
